### PR TITLE
feat: support specify the page number of the pdf

### PR DESCRIPTION
**Pull request by Elilif**
You can use `#+attr_org: :page NUM' to specify the page number.

### CODE REVIEW

**Comment by shg** [comment]
Hi @Elilif

Thank you very much for the PR! And sorry for taking time to respond.

Adding the option for selecting page is great and must be useful. One request is to remove pdftocairo support from this PR. I was also thinking to support for pdftocairo (#1) but I prefer to keep pdf2svg work as well. So could you make this only for page selection and make a seperate PR for pdftocairo support if you like?

**Comment by Elilif** [comment]
> One request is to remove pdftocairo support from this PR

This is my negligence, my original intention was to test `pdftocairo` and I forgot to make new branch. Sorry for that.

**Comment by shg** [comment]
Hi @Elilif  I have two more requests. Sorry I didn't mentioned these together with the previous one.

There are lines with no change except tabs are replaced with spaces. Please change them back to tabs. Unfortunately this code uses old-fashioned mixed tab/space for indentation.

Please remove the change to define-minor-mode call from this PR. I understand the current code uses old form and would be better updated but I'd like to make it separate from this PR.

**Comment by Elilif** [comment]
@shg  I have updated this PR.

**Comment by shg** [comment]
Merged and updated README. Thank you!

**Pull request merged**
